# Generated by Django 4.0.2 on 2022-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproducto',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
