# Generated by Django 4.0.4 on 2022-05-11 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_tipo_categoriaproducto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='categoriaproducto',
            table='db_categoria_producto',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='db_producto',
        ),
        migrations.AlterModelTable(
            name='tipoproducto',
            table='db_tipo_producto',
        ),
    ]
